sudo: required
before_install:
  - sudo apt-get install libtorrent-rasterbar
  - sudo apt-get install libboost-all-dev

language: cpp

compiler:
  - gcc

install:
  - "[ $CXX = g++ ] && export CXX=g++-6 || true"

script:
  - make
