sudo: required
dist: trusty
language: cpp
compiler: g++
install: export CXX="g++-7"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:deluge-team/develop
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y g++-7 libtorrent-rasterbar9 libtorrent-rasterbar-dev libtorrent-rasterbar-dbg libboost-all-dev

script:
  - g++-7 --version
  - mkdir bin
  - make

notifications:
  email: false