[api]
	address = "0.0.0.0"
	port = 8040
[log]
	severity = "debug"
	max_files = 3
	file_path = "/mnt/DATA/Codacao/bitsleek/log/bitsleek-log.txt"
	max_size = 5242880
[libtorrent]
	[libtorrent.extensions]
		smart_ban_plugin = "enabled"
		ut_metadata_plugin = "enabled"
		ut_pex_plugin = "enabled"
[directory]
	session_state_path = "/mnt/DATA/Codacao/bitsleek/state/session.state"
	torrent_file_path = "/mnt/DATA/Codacao/bitsleek/state/torrents/"
	fastresume_path = "/mnt/DATA/Codacao/bitsleek/state/fastresume/"
	download_path = "/mnt/DATA/Codacao/bitsleek/temp/downloads/"
