[api]
	address = "0.0.0.0"
	port = 8040
[log]
	severity = "debug"
	max_files = 3
	file_path = "log/bitsleek-log.txt"
	max_size = 5242880
[libtorrent]
	[libtorrent.extensions]
		ut_metadata_plugin = "enabled"
		ut_pex_plugin = "enabled"
		smart_ban_plugin = "enabled"
[directory]
	torrent_file_path = "state/torrents/"
	database_path = "state/database/bitsleek.db"
	session_state_path = "state/session.state"
	fastresume_path = "state/fastresume/"
	download_path = "temp/downloads/"
