[api]
	address = "0.0.0.0"
	port = 8040
[directory]
	torrent_file_path = "/mnt/DATA/Codacao/bitsleek/state/torrents/"
	save_session_path = "/mnt/DATA/Codacao/bitsleek/state/session.state"
	download_path = "/mnt/DATA/Codacao/bitsleek/temp/downloads/"
	fastresume_path = "/mnt/DATA/Codacao/bitsleek/state/fastresume/"
[log]
	max_files = 3
	severity = "debug"
	max_size = 5242880
	file_path = "/mnt/DATA/Codacao/bitsleek/log/bitsleek-log.txt"
