[log]
	severity = "debug"
	file_path = "log/bitsleek-log.txt"
	max_size = 5242880
[api]
	address = "0.0.0.0"
	port = 8040
[directory]
	database_path = "state/database/bitsleek.db"
	torrent_file_path = "state/torrents/"
	session_state_path = "state/session.state"
	download_path = "temp/downloads/"
	fastresume_path = "state/fastresume/"
[libtorrent]
	[libtorrent.extensions]
		smart_ban_plugin = "enabled"
		ut_metadata_plugin = "enabled"
		ut_pex_plugin = "enabled"
