[libtorrent]
	[libtorrent.extensions]
		ut_metadata_plugin = "enabled"
		ut_pex_plugin = "enabled"
		smart_ban_plugin = "enabled"
[directory]
	download_path = "temp/downloads/"
	fastresume_path = "state/fastresume/"
	session_state_path = "state/session.state"
	database_path = "state/database/torrentine.db"
	torrent_file_path = "state/torrents/"
[log]
	severity = "debug"
	max_size = 5242880
	file_path = "log/torrentine-log.txt"
[api]
	port = 8040
	address = "0.0.0.0"
